# Site settings
name: Less Or More
email: kangjunfengknight@gmail.com
author: Krien
url: http://www.github.com/kangjunfeng.github.io/
resume_site: http://www.github.com/kangjunfeng.github.io/
github: http://www.github.com/kangjunfeng.github.io/
baseurl: "/Learn more"
description: Actually, less is more!
meta_description: 
motto: It's our wits that make us men.
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kangjunfeng
highlighter: Pygments

# Build settings
markdown: kramdown